# print 5 + 1.0;
# print 1.5d + 1;
# print 1 + 0.2d;
print 1.0 / 2.0d + 3;
# print 1.5d + 1;
# print 0.2d + 1; # solo

# float operations not working, doubles are

# print 2147483648l;
# print 1 + 2;
# print 1l + 2l;

# print 1 + 100l;

# print (let x = 10 in x) + (let x = 20 in let y = 30 in x+y)
# print 100 / 2
# print 2 / 100
# set x = 10
# print x
# set x = 15
# print 15 + 5
# print x + 5
# set y = x * (x+1) / 2
# print y
# print (let x = 10 in x) + (let x = 20 in let y = 30 in x+y)
# set x = 20
# print x
# set x = x + (let x = 3 in x) + x
# print x
